language: php

dist: xenial

php:
  - 7.3

before_script:
  - composer require cakephp/cakephp-codesniffer:^3.3
  - composer install

script:
  - vendor/bin/phpcs -p src/ tests/ config/

notifications:
  email: false
