name: remote deploy
on: [push]
jobs:

  build:
    name: remote deploy
    runs-on: ubuntu-latest
    steps:
    - name: remote deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: bash /home/deploy/deploy_cakephp_org.sh
